language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  
addons:
  firefox: "40.0"

sudo: required

before_script:
  - ./tests/setup/before_script.sh
  - ./tests/setup/apache.sh
  - ./tests/setup/selenium.sh

script: 
  # Use phpunit or vendor/bin/phpunit to start tests.  
  # vendor/bin/phpunit is the best option to run the tests. Because this one 
  # is installed via composer. 
  # Not running phpunit installed via composer gives errors, has to do with the 
  # versions of the dependencies. 
  - vendor/bin/phpunit -v tests/simpleTest.php 
  - vendor/bin/phpunit tests/ 
  - vendor/bin/phpunit -v -c tests/phpunit.xml 

notifications: 
  email:
   recipients:
      - d.asscheman@lumc.nl
   on_success: never
   ## [always|never|change] # default: change
   on_failure: always 
   ## [always|never|change] # default: always